apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-et-pvc
  namespace: expense-tracker-ns

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-storage

  resources:
    requests:
      storage: 5Gi
